spec:
  template:
    spec:
      containers:
        - name: nodejs-mem
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup